### ISSUE TITLE
Get showcased in README by contributing a small blog site for our repository in your favourite stack for Hacktoberfest 2020

### ISSUE THREAD

**Issue by aniketchaudhari3** [aniketchaudhari3/hacktoberfest2020#12]
Contributors interested can create a small blog/website writing about their experience in contributing for Hacktoberfest 2020. Contributors profiles will be showcased in the Readme.

**Comment by Ranner198** [comment]
Any particular requests for this? just a blog/landing page for you guys (HTML5/CSS3) any particular backend? (Node JS)

**Comment by beertocode** [comment]
May i be assigned this issue please ?

**Comment by aniketchaudhari3** [comment]
Hi @Ranner198 and @beertocode, feel free to use any frontend and backend you like, it'll be better if it would be a JAMstack webapp built with MERN or Vue, any would do. Thanks.

**Comment by aniketchaudhari3** [comment]
A suggestions - Gatsby blog starter
