### ISSUE TITLE
Add a new list.py file to the pythons solution.

### ISSUE THREAD

**Issue by swetasahoo29** [aniketchaudhari3/hacktoberfest2020#27]
I want to expand the contribution on Data Structures.
So I want to add a list.py solution to pythons  solution. 
@aniketchaudhari3

**Comment by swetasahoo29** [comment]
Please assign me this task.
@aniketchaudhari3

**Comment by aniketchaudhari3** [comment]
Hi @swetasahoo29 , I've assigned this issue to you.

**Comment by swetasahoo29** [comment]
Thankyou.

**Comment by swetasahoo29** [comment]
Thankyou for merging but the issue is still open can you please close it.
