### ISSUE TITLE
Submit your favourite Data Structures and Algorithms programs in any language for Hacktoberfest 2020

### ISSUE THREAD

**Issue by aniketchaudhari3** [aniketchaudhari3/hacktoberfest2020#5]

**Comment by chakravarthi-v** [comment]
@aniketchaudhari3  can u assign me this

**Comment by aniketchaudhari3** [comment]
Hi,
I have assigned you this issue.
Thanks

**Comment by GanapathiSubramanian** [comment]
@aniketchaudhari3  Can you assign me?

**Comment by aniketchaudhari3** [comment]
Hi @GanapathiSubramanian ,
I've assigned this issue to you

**Comment by ronika-das** [comment]
I would like to contribute. Can you also assign me?

**Comment by aniketchaudhari3** [comment]
Hi @ronika-das I've assigned this issue to you.

**Comment by chakravarthi-v** [comment]
@ronika-das I have completed #13

**Comment by pawank0411** [comment]
@aniketchaudhari3 Can you assign me this

**Comment by Deepak290701** [comment]
@aniketchaudhari3  can you assign me this task .

**Comment by aniketchaudhari3** [comment]
hI @Deepak290701 @pawank0411 I have assigned you this task.

**Comment by aniketchaudhari3** [comment]
Hi @pawank0411 thankyou for sharing the update, I've updated the topic as hacktoberfest-accepted

**Comment by poojagorai** [comment]
@aniketchaudhari3 please assign me

**Comment by aniketchaudhari3** [comment]
Hi @poojagorai , I've assigned this task

**Comment by Dhar15** [comment]
Hey, could you assign me?

**Comment by Mayank-Khurmai** [comment]
Assign to me, as i want to participate and help in this

**Comment by aniketchaudhari3** [comment]
Assigned this issue to @Dhar15 and @Mayank-Khurmai

**Comment by Mayank-Khurmai** [comment]
> In Reply To  :-  Assign to me, as i want to participate and help in this

issue #5
Added the Palindrome Code in JavaScript #37

Added in the Solution>JS Folder 

You can verify for your satisfaction and if you want to assign more then let me know

Commit Link -- [https://github.com/aniketchaudhari3/hacktoberfest2020/pull/37/files]


Please merge it

**Comment by shobhnanayak99** [comment]
@aniketchaudhari3 can you assign me?

**Comment by shiladityaroy212** [comment]
Please assign me this . I can contribute in this

**Comment by anjali-coder** [comment]
@aniketchaudhari3 I would like to contribute. Can you assign this to me?

**Comment by Janitha133** [comment]
I would like to contribute in this

**Comment by Apoorv-cloud** [comment]
Hello. I would like to contribute in this issue. Kindly assign me this task.

**Comment by einhawking** [comment]
Hi, can you please assign me this. I would like to contribute in this.

**Comment by sidhantgusain** [comment]
i would like to contribute.
can you assign me.
