### ISSUE TITLE
Create folders for different programming languages for contributers to submit

### ISSUE THREAD

**Issue by aniketchaudhari3** [aniketchaudhari3/hacktoberfest2020#6]
Contributer can create different folders for languages like C++, JavaScript, Python etc. and move existing programs into respective folders

**Comment by DS-73** [comment]
Hello, can you assign this issue to me I can do it.

Thanks

**Comment by aniketchaudhari3** [comment]
Hi Dhruv, I have assigned this issue to you. Thanks

**Comment by prathmesh-Chaudhari05** [comment]
Can you Assign this Issue to Me, I want to Contribute for Python Language.

**Comment by aniketchaudhari3** [comment]
Hi, You are assigned to this issue.
